Update d3
Old version of d3 has a bad externs file that can cause Closure compiler to throw.

```
-> Closure - Optimizing ...
Closure compilation failed with 1 errors
--- EXTERNS:/Users/.../.m2/repository/cljsjs/d3/4.2.2-0/d3-4.2.2-0.jar!/cljsjs/d3/common/d3.ext.js:670
Object literal contains illegal duplicate key "scaleSequential", disallowed in strict mode
```